jobs:
- job: Benchmarks
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 360
  strategy:
    matrix:
      Python_38:
        python.version: 3.8
        name: "Python 3.8 - benchmarks"

  steps:

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - script: |
      ls -ahl
      env
      pwd
      gcc --version
      python --version
    displayName: 'Debug information'

  - script: |
      python -m pip install --upgrade pip
      python -m pip install --no-cache-dir -r requirements.txt
      python -m pip install --no-cache-dir -r requirements-optional.txt
      python -m pip install asv
    displayName: 'Install requirements'

  - script: |
      python -m pip freeze
    displayName: 'Debug information 2'

  - script: |
      python -m asv machine --yes
      git log --pretty=format:'%h' -n 1 > hashestobenchmark.txt
      cat hashestobenchmark.txt
      python -m asv run HASHFILE:hashestobenchmark.txt
    displayName: 'Run the benchmarks'
    workingDirectory: asv_benchmarks/

  - script: |
      git log --pretty=format:'%h' -n 1 | xargs python -m asv show
      git log --pretty=format:'%h' -n 1 | xargs python -m asv show > ../benchmark_results.txt
    displayName: 'Print and save results'
    workingDirectory: asv_benchmarks/

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'benchmark_results.txt'
      artifactName: 'Benchmarks'
    displayName: 'Publish the benchmarks'
